# Generated by Django 5.2.6 on 2025-10-01 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                ("cart_id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Crop",
            fields=[
                ("crop_id", models.AutoField(primary_key=True, serialize=False)),
                ("crop_name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("farmer", "Farmer"),
                            ("wholesaler", "Wholesaler"),
                            ("admin", "Admin"),
                        ],
                        max_length=50,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "phone_number",
                    models.CharField(default="0000000000", max_length=15, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="MarketPrice",
            fields=[
                (
                    "market_price_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("location", models.CharField(max_length=20)),
                (
                    "price_per_unit",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "crop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mlimi_zone.crop",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                ("order_id", models.AutoField(primary_key=True, serialize=False)),
                ("price", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "status",
                    models.CharField(
                        choices=[("unpaid", "Unpaid"), ("paid", "Paid")],
                        default="unpaid",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="mlimi_zone.cart",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("payment_id", models.AutoField(primary_key=True, serialize=False)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "payment_status",
                    models.CharField(
                        choices=[("completed", "Completed"), ("failed", "Failed")],
                        max_length=20,
                    ),
                ),
                (
                    "transaction_ref",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mlimi_zone.order",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProduceListing",
            fields=[
                ("croplisting_id", models.AutoField(primary_key=True, serialize=False)),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "crop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mlimi_zone.crop",
                    ),
                ),
                (
                    "farmer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="produce_listings",
                        to="mlimi_zone.user",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="order",
            name="croplisting",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="mlimi_zone.producelisting",
            ),
        ),
        migrations.CreateModel(
            name="SMSLogs",
            fields=[
                ("smslog_id", models.AutoField(primary_key=True, serialize=False)),
                ("message_body", models.TextField()),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("delivered", "Delivered"), ("failed", "Failed")],
                        max_length=10,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sms_logs",
                        to="mlimi_zone.user",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="order",
            name="wholesaler",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="mlimi_zone.user",
            ),
        ),
        migrations.AddField(
            model_name="cart",
            name="wholesaler",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="mlimi_zone.user"
            ),
        ),
    ]
