# Generated by Django 5.2.6 on 2025-10-01 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mlimi_zone", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="USSDSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.CharField(max_length=100, unique=True)),
                ("phone_number", models.CharField(max_length=15)),
                ("data", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
